# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-16 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personalisation', '0009_auto_20170516_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='GemUserProfileRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[(b'gender', 'gender')], max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('segment', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalise_gemuserprofilerule_related', related_query_name='%(app_label)s_%(class)ss', to='personalisation.Segment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
