# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-16 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personalisation', '0009_auto_20170516_1129'),
        ('personalise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileDataRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[(b'user__date_joined', b'User - Date Joined'), (b'userprofile__date_of_birth', b'User Profile - Date Of Birth'), (b'userprofile__gender', b'User Profile - Gender')], max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('segment', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalise_profiledatarule_related', related_query_name='%(app_label)s_%(class)ss', to='personalisation.Segment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='gemuserprofilerule',
            name='segment',
        ),
        migrations.DeleteModel(
            name='GemUserProfileRule',
        ),
    ]
