# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-16 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalise', '0003_auto_20170516_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledatarule',
            name='operator',
            field=models.CharField(choices=[(b'lt', 'Less than'), (b'lte', 'Less than or equal'), (b'gt', 'Greater than'), (b'gte', 'Greater than or equal'), (b'eq', 'Equal'), (b'neq', 'Not equal'), (b'old', 'Older than'), (b'ygr', 'Younger than'), (b'eqa', 'Of age'), (b'reg', 'Regex')], max_length=3),
        ),
    ]
